chore: db checks added

diff --git a/bin/cms b/bin/cms
--- a/bin/cms
+++ b/bin/cms
@@ -47,13 +47,19 @@ if [ "$1" = "--setup" ]; then
     read -p "🌐 Enter site name: " site_name
     read -p "🔗 Enter site URL: " site_url
     read -p "🔌 Enter port number: " port_number
-    read -p "🗄️  Enter database host: " db_host
+    read -p "🗄️ Enter database host: " db_host
     read -p "💾 Enter database name: " db_name
     read -p "👤 Enter database user: " db_user
     read -sp "🔒 Enter database password: " db_password
     echo ""
     echo "🗄️ Configuring database..."
     mysql -h "$db_host" -u root -p -e "CREATE USER IF NOT EXISTS '$db_user'@'$db_host' IDENTIFIED BY '$db_password'; GRANT ALL PRIVILEGES ON \`$db_name\`.* TO '$db_user'@'$db_host'; FLUSH PRIVILEGES;"
+    if [ $? -eq 0 ]; then
+        echo -e "✔ Database user '$db_user' configured successfully."
+    else
+        echo -e "✘ Failed to configure database user: '$db_user'. Please check your credentials and try again."
+        exit 1
+    fi
     read -p "🗄️ Would you like to create the database now? (y/n): " create_db_choice
     echo ""
     if [[ "$create_db_choice" =~ ^[Yy]$ ]]; then
@@ -74,16 +80,19 @@ if [ "$1" = "--setup" ]; then
     sed -i "s/^DB_DATABASE=.*/DB_DATABASE=${db_name}/" .env
     sed -i "s/^DB_USERNAME=.*/DB_USERNAME=${db_user}/" .env
     sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=${db_password}/" .env
-
     echo ""
     echo -e "✔ Environment variables updated successfully."
     echo ""
-    cp bin/env/host/site_config /etc/nginx/sites-available/"${site_name}"
+    echo "⚙️ Setting up Nginx configuration..."
+    sudo cp bin/env/host/site_config /etc/nginx/sites-available/"${site_name}"
     sed -i "s/{{DOMAIN_NAME}}/$(echo ${site_url} | sed 's|https\?://||')/g" /etc/nginx/sites-available/"${site_name}"
     sed -i "s/{{PORT}}/${port_number}/g" /etc/nginx/sites-available/"${site_name}"
     sed -i "s|{{DOCUMENT_ROOT}}|$(pwd)|g" /etc/nginx/sites-available/"${site_name}"
     ln -sf /etc/nginx/sites-available/"${site_name}" /etc/nginx/sites-enabled/"${site_name}"
     echo "✔ Nginx configuration created and symlink established."
+    echo "🔄 Restarting Nginx to apply changes..."
+    sudo systemctl restart nginx
+    echo -e "✔ Nginx restarted successfully."
 fi
 
 
